# Generated by Django 4.0.5 on 2022-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cruiseroute',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
